[build]
rustflags = [ "-Cforce-frame-pointers=yes" ]

[patch.crates-io]
openxr = { path = "./openxrs/openxr" }
vulkano = { git = "https://github.com/vulkano-rs/vulkano" }

[alias]
xtask = "run --package xtask --"
